const SET_CUR_PLAY_LIST = 'SET_CUR_PLAY_LIST'
const SET_CUR_PLAY_INDEX = 'SET_AUDIO_INDEX'
const SET_CUR_SHOW_LIST = 'SET_CUR_SHOW_LIST'
const SET_PLAY_SATE = 'SET_PLAY_SATE' // 设置当前的播放状态
const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export {
  SET_CUR_PLAY_LIST,
  SET_CUR_PLAY_INDEX,
  SET_CUR_SHOW_LIST,
  SET_PLAY_SATE, // 设置当前的播放状态
  SET_FULL_SCREEN
}
